---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install Packages
    package:
      name:
        - htop
        - snapd
        - tmux
        - vim
        - python3-psutil
        - locate

  - name: Install Snap Packages
    snap:
      name: signal-desktop
      classic: yes

  - name: Copy Wallpaper File
    copy:
      src: files/wallpaper.png
      dest: /usr/share/brackgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: Set Wallpaper
    become_user: thgmatt
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: Set Wallpaper Position
    become_user: thgmatt
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: Copy .bashrc File
    copy:
      src: files/bashrc
      dest: /home/thgmatt/.bashrc
      owner: thgmatt
      group: thgmatt

  - name: Add Ansible User
    user:
      name: velociraptor
      system: yes

  - name: Set Up Sudo for Ansible User
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: Add Ansible-Pull Cron Job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/THGMatt/ansible_desktop.git